decide/base/urls.py
urlpatterns = []

decide/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.home, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/',views.logout_view, name='logout'),
    path('assigned_census/', views.assigned_census, name='assigned_census'),
]

decide/decide/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from rest_framework_swagger.views import get_swagger_view

from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _


schema_view = get_swagger_view(title='Decide API')

urlpatterns = [
    path('i18n/', include("django.conf.urls.i18n")),
]

urlpatterns +=  i18n_patterns(
    path(_('admin/'), admin.site.urls),
    path('doc/', schema_view),
    path('gateway/', include('gateway.urls')),
    path('', include('comentarios.urls')),
    path('', include('base.urls')),
    path('', include('core.urls')),
    path('accounts/' , include('allauth.urls')),
)


for module in settings.MODULES:
    urlpatterns += [
        path('{}/'.format(module), include('{}.urls'.format(module)))
    ]

decide/base/models.py
from django.db import models


class BigBigField(models.TextField):
    def to_python(self, value):
        if isinstance(value, str):
            return int(value)
        if value is None:
            return 0
        return int(str(value))

    def get_prep_value(self, value):
        if value is None:
            return 0
        return str(value)

    def from_db_value(self, value, expression, connection):
        if value is None:
            return 0
        return int(value)


class Auth(models.Model):
    name = models.CharField(max_length=200)
    url = models.URLField()
    me = models.BooleanField(default=False)

    def __str__(self):
        return self.url


class Key(models.Model):
    p = BigBigField()
    g = BigBigField()
    y = BigBigField()
    x = BigBigField(blank=True, null=True)

    def __str__(self):
        if self.x:
            return "{},{},{},{}".format(self.p, self.g, self.y, self.x)
        else:
            return "{},{},{}".format(self.p, self.g, self.y)

decide/core/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django import forms

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Nombre de usuario',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Contraseña',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Enter a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Nombre de usuario',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'placeholder': 'correo electrónico',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Contraseña',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repetir la contraseña',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

decide/base/views.py
from django.shortcuts import render

# Create your views here.

decide/core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from census.models import Census
from voting.models import Voting
from django.utils import timezone
from django.contrib.auth.decorators import login_required



from .forms import SignUpForm

def home(request):
  if 'django_language' in request.session:
     del request.session['django_language']

  return render(request, 'core/index.html', {"usuario": request.user})

def signup(request):
  if request.method == 'POST':
    form = SignUpForm(request.POST)

    if form.is_valid():
      form.save()
      return redirect('/login/' )
  else:
    form = SignUpForm()

  return render(request, 'core/signup.html', {
    'form': form
  })
def logout_view(request):
  logout(request)
  return redirect('/')


@login_required(login_url='/no_autenticado')
def assigned_census(request):
    current_datetime = timezone.now()

    # Filtrar los censos asignados
    census = Census.objects.filter(voter_id=request.user.id)

    # Filtrar las votaciones que tienen fecha de inicio pero no de finalización
    votings = []
    for c in census:
        vot = Voting.objects.filter(id=c.voting_id, start_date__isnull=False, end_date__isnull=True, start_date__lte=current_datetime).first()
        if vot:
            votings.append(vot)

    return render(request, 'core/assigned_census.html', {"census": census, "votings": votings})

decide/core/templates/core/assigned_census.html
{% extends "core/base.html" %}

{% load static %}
{% load i18n %}

{% block title %} {% trans "Censos asignados" %} {% endblock title %}

{% block header %}
{% endblock header %}

{% block description %} {% trans "Tienes estos census asignados" %}{% endblock description %}

{% block content %}
<h2 class="text-center">{% trans "Lista de census" %}</h2>
<table class="table mx-auto">
  <thead>
    <tr>
      <th>{% trans "ID de la votación" %}</th>
      <th>{% trans "Nombre de la votación" %}</th>
      <th>{% trans "Fecha de inicio" %}</th>
    </tr>
  </thead>
  <tbody>
    {% for vot in votings %}
      <tr>
        <td class="destino-clickable"><a href="{% url 'booth' voting_id=vot.id %}">{{ vot.id }}</a></td>
        <td>{{ vot.name }}</td>
        <td>{{ vot.start_date }}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>
</div>

<style>
.table {
  width: 80%;
  margin: auto;
}

.destino-clickable {
  cursor: pointer;
  text-decoration: underline;
  color: blue;
}
</style>
{% endblock content %}

decide/core/templates/core/base.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}

<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock title %} - VotacionesM4</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static "css/base.css" %}">

  {% block header %}{% endblock header %}
</head>
<body>
 <style>
    body {
      background-color: #f4f4f4; /* Color de fondo suave */
      font-family: 'Lato', sans-serif; /* Fuente personalizada */
      margin: 0;
      padding: 0;
    }
    /* Resto de tu CSS ... */
  </style>
  <header>
    <section class="base-header-primary">
        <a href="{% url "core:index" %}">
            <h1><strong>VotacionesM4</strong></h1>
        </a>
        {%get_current_language as LANGUAGE_CODE %}

        <form action="{% url 'set_language' %}" method="POST" class="form-inline" style="margin-right:20px">
            {% csrf_token %}
            <input type="hidden" name="text" value="{{ redirect_to }}" class="form-control">
            <select name="language" id="languageSelect" class="form-control mr-2">
              {% get_available_languages as LANGUAGES %}
              {% get_language_info_list for LANGUAGES as languages %}
              {% for language in languages %}
                <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected {% endif %}>
                  {{ language.name_local }} {{ language.code }}
                </option>
              {% endfor %}
            </select>
            <button type="submit" class="btn btn-primary">{% trans "Traducir" %}</i></button>
        </form>
    
        <nav>
            {% if request.user.is_authenticated %}
            <a class="btn btn-outline-success" onClick="window.location.href='/assigned_census'"
              role="button">{% trans "Votaciones Asignadas" %}</a>
            <a class="btn btn-outline-success"  onClick="window.location.href='/ver-comentarios'" role="button">{% trans "Votaciones Finalizadas" %}</a>

            <a class="btn btn-outline-success" onClick="redirectToHome()" role="button">{% trans "Home" %}</a>

            <a class="btn btn-outline-success" onClick="window.location.href='/logout'"
            role="button">{% trans "Cerrar Sesión" %}</a>




            <script>
                function redirectToHome() {
                    window.location.href = '{% url "core:index" %}';
                }
            </script>

            {% else %}
            <a class="btn btn-outline-success" href="{% url "core:signup" %}" role="button">{% trans "Registro" %}</a>
            <a class="btn btn-outline-success" href="{% url "core:login" %}" role="button">{% trans "Iniciar Sesion" %}</a>

            <script>
                function redirectToHome() {
                    window.location.href = 'http://localhost:8080/';
                }
            </script>
            {% endif %}
        </nav>
    </section>
    <section class="base-header-secondary">
        <h2>{% block description %}{% endblock description %}</h2>
    </section>
  </header>
  <main>
    {% block content %}
    {% endblock content %} 
  </main>
  <footer class="text-center text-lg-start bg-light text-muted">
    <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
      <div class="me-5 d-none d-lg-block">
        <span>{% trans "Conecta con nosotros en nuestras redes sociales:" %}</span>
      </div>
      <div>
        <a href="https://www.facebook.com/UniversidaddeSevillaoficial" target="_blank" class="me-4 text-reset">
          <i class="fab fa-facebook-f" , style="margin-right:5px"></i>
          Facebook
        </a>
        <a href="https://twitter.com/unisevilla" target="_blank" class="me-4 text-reset">
          <i class="fab fa-twitter" , style="margin-right:5px"></i>
          Twitter
        </a>
        <a href="https://www.youtube.com/user/UniversidaddeSevilla" target="_blank" class="me-4 text-reset">
          <i class="fab fa-youtube" , style="margin-right:5px"></i>
          YouTube
        </a>
        <a href="https://www.instagram.com/unisevilla/" target="_blank" class="me-4 text-reset">
          <i class="fab fa-instagram" , style="margin-right:5px"></i>
          Instagram
        </a>
        <a href="https://www.linkedin.com/school/universidad-de-sevilla/" target="_blank" class="me-4 text-reset">
          <i class="fab fa-linkedin" , style="margin-right:5px"></i>
          Linkedin
        </a>
      </div>
    </section>
    <section class="">
      <div class="container text-center text-md-start mt-5">
        <div class="row mt-3">
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
            <h6 class="text-uppercase fw-bold mb-4">
              <i class="fas fa-gem me-3"></i> {% trans "Universidad de Sevilla" %}
            </h6>
            <p>
              {% trans "Somos una de las universidades más antiguas, teniendo mas de 500 años de historia, y la tercera universidad mas grande de España" %}
            </p>
          </div>
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
            <h6 class="text-uppercase fw-bold mb-4">
              {% trans "Productos" %}
            </h6>
            
            <p>
              <a href="https://www.informatica.us.es/" target="_blank" class="text-reset">{% trans "Universidad de Informática" %}</a>
            </p>
          </div>
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            <h6 class="text-uppercase fw-bold mb-4">{% trans "Contacto" %}</h6>
            <p><i class="fas fa-home me-3"></i> {% trans "Sevilla, Av. de la Reina Mercedes 41012, ES" %}</p>
            <p>
              <i class="fas fa-envelope me-3"></i>
              VotacionesM4@votaciones.com
            </p>
            <p><i class="fas fa-phone me-3"></i> + 34 642 24 40 00</p>
          </div>
        </div>
      </div>
    </section>
    
  </footer>
</body>
</html>

decide/core/templates/core/index.html
{% extends "core/base.html" %}

{% load static %}
{% load i18n %}

{% block title %} {% trans "Home" %} {% endblock title %}

{% block header %}

{% endblock header %}

{% block description %} 
{% trans "¿Quienes somos?" %}
{% endblock description %}


{% block content %}
  <article>
    <div class="index-div-first-section-header" style="margin-left:20px">
      <h3>{% trans "Bienvenido" %} {{ usuario }}</h3>
    
    </div>
    <section class="index-section-description" style="margin-left:20px">
      <p>
        {% trans "En " %}<strong>VotacionesM4</strong>{% trans ", nos dedicamos a la creación de votaciones para cualquier tipo de evento, ya sea para una empresa, una asociación, un grupo de amigos, etc." %} 
      </p>
    </section>
    {% if request.user.is_authenticated %}
    <a class="btn btn-outline-success" onClick="window.location.href='/voting/create_voting'" role="button">Crear Votación</a>
    {% endif %}

  </article>
{% endblock content %}

decide/core/templates/core/login.html
{% extends "core/base.html" %}



{% load static %}
{% load i18n %}

{% block title %} {% trans "Inicia Sesión" %} {% endblock title %}

{% block header %}
  <link rel="stylesheet" href="{% static "css/login.css" %}">
{% endblock header %}

{% block content %}
  <div class="login-container">
    <div class="login-form">
      <div class="login-logo">
        <i class="fas fa-crow me-2" style="color: #007bff;"></i> {% trans "Iniciar Sesión" %}
      </div>

      <form method="post" action="{% url 'core:login' %}">
        {% csrf_token %}

        <div class="mb-4">
          <label for="form2Example18" class="form-label" style="width: 100%; margin: 0 auto; text-align: center; margin-bottom: 10px;">{% trans "Nombre de usuario" %}</label>
          <div class="input-container" style="width: 80%; margin: 0 auto; text-align: center;">
                  {{ form.username }}
          </div>
        </div>

        <div class="mb-4">
          <label for="form2Example28" class="form-label" style="width: 100%; margin: 0 auto; text-align: center;     margin-bottom: 10px;">{% trans "Contraseña" %}</label>
          <div class="input-container" style="width: 80%; margin: 0 auto; text-align: center;">
          {{ form.password }}
           </div>

        </div>

       

        <div class="mb-4">
          <button class="btn btn-info btn-lg btn-block login-btn"  type="submit">{% trans "Log in" %}</button>
        </div>

        <p>{% trans "No tienes una cuenta todavía?" %} <a href="{% url 'core:signup' %}" class="link-info">{% trans "Regístrate aquí" %}</a></p>
        {% load socialaccount %}
        {% providers_media_js %}

        <a class="fab fa-google size social text-info custom-google-login" aria-hidden="true" href="{% provider_login_url 'google' %}">{% trans "Iniciar sesión con Google" %}</a>

      </form>
    
    </div>
  </div>
{% endblock content %}

decide/core/templates/core/signup.html
{% extends "core/base.html" %}

{% load static %}
{% load i18n %}

{% block title %} Regístrate {% endblock title %}

{% block header %}
  <link rel="stylesheet" href="{% static "css/signup.css" %}" >
{% endblock header %}

{% block content %}
  <section class="vh-100">
    <div class="container">
      <div class="row justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card">
            <div class="card-body p-6">
              <form method="post" action=".">
                {% csrf_token %}
                <h3 class="text-uppercase text-center mb-5">{% trans "Regístrate" %}</h3>

                <div class="mb-4">

             <label for="form2Example18" class="form-label" style="width: 100%; margin: 0 auto; text-align: center; margin-bottom: 10px;">{% trans "Nombre de usuario" %}</label>
              <div class="input-container" style="width: 80%; margin: 0 auto; text-align: center;">

                  {{ form.username }}
                </div>

                <div class="mb-4">
                <label for="form2Example18" class="form-label" style="width: 100%; margin: 0 auto; text-align: center; margin-bottom: 10px;">{% trans "Correo electrónico" %}</label>
              <div class="input-container" style="width: 80%; margin: 0 auto; text-align: center;">
                  {{ form.email }}
                </div>

                <div class="mb-4">
                  <label for="form2Example18" class="form-label" 
                                      style="width: 100%; margin: 0 auto; text-align: center; margin-bottom: 10px;">
                  {% trans "Contraseña" %}</label>
                  <div class="input-container" style="width: 80%; margin: 0 auto; text-align: center;">
                  {{ form.password1 }}
                </div>

                <div class="mb-4">
                <label for="form2Example18" class="form-label" 
                                      style="width: 100%; margin: 0 auto; text-align: center; margin-bottom: 10px;">
                  {% trans "Confirmación de Contraseña" %}</label>
                  <div class="input-container" style="width: 80%; margin: 0 auto; text-align: center;  margin-bottom: 10px; ">
    
                  {{ form.password2 }}
                </div>

                {% if form.errors or form.non_field_errors %}
                  <div class="mb-3 p-6 bg-red-100 rounded-x1"> 
                    {% for field in form %}
                      {{ field.errors }}
                    {% endfor %}
                    {{ form.non_field_errors }}
                  </div>
                {% endif %}

                <div class="form-group text-center">
                  <button type="submit" class="btn btn-custom btn-lg text-body">{% trans "Registrarse" %}</button>
                </div>
              </form>

              <p class="text-center text-muted mt-3">{% trans "¿Ya tienes una cuenta?" %} <a href="{% url 'core:login' %}" class="fw-bold text-body"><u>{% trans "Inicia sesión aquí" %}</u></a></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}